language: python

python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5

sudo: true

matrix:
    fast_finish: true
    allow_failures:
        - 3.5

before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install -y libgdal1-dev

install:
 - make
 - python setup.py --quiet install

script:
 - python setup.py test
