language: python

python:
 - 3.6
 - 3.7
 - 3.8

sudo: true

cache:
  directories:
    - $HOME/.cache/pip

env:
  - NUMPY=no
  - NUMPY=yes

before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install -y libgdal1-dev
 - pip install docutils
 - if [[ $NUMPY == "yes" ]]; then pip install numpy; fi
 - if [[ $NUMPY == "no" ]]; then pip uninstall -y numpy; fi

install:
 - make
 - pip install -e .[azimuth,shape]

script:
 - python setup.py test
